name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  check:
    name: âœ… check
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Install dependencies
        run: npm install

      - name: ğŸ¦‹ Check format
        run: npm run check:format

      - name: ğŸ“‘ Check lint
        run: npm run check:lint


  test:
    name: ğŸ§¾ Test app
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v4
         
      - name: Install dependencies
        run: npm install

      - name: ğŸ§ª Run tests
        run: npm run test

  build:
    name: ğŸ‘· Build app
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: â¬‡ï¸ Checkout project
        uses: actions/checkout@v4

      - name: âš’ï¸ Build project
        run: npm run build
